#!/bin/sh
#
# Copyright (c) 2011, 2012, The Trusted Domain Project.  All rights reserved.
#

YEAR=`date +%Y`
LASTYEAR=$(($YEAR - 1))

for i in `git diff develop --name-only @{$LASTYEAR-12-31} | grep -F -v .jpg | grep -F -v contrib/ | grep -F -v docs/`
do
	if test -f $i
	then
		if grep -q Copyright $i
		then
			if ! grep -q Copyright.\*$YEAR $i
			then
				echo $i
			fi
		fi
	fi
done
