# Generated by pykickstart v3.29
#version=40

%pre
DISK=$(basename -a $(ls -1 /dev/*da))

# Disk partitioning information
echo part /boot/efi --fstype="efi" --fsoptions="umask=0077,shortname=winnt" --ondisk=${DISK} >> /tmp/include-disk
echo part /boot --fstype="ext2" --size=1024 --ondisk=${DISK} >> /tmp/include-disk
echo part pv.1 --fstype="lvmpv" --size=1024 --grow --ondisk=${DISK} >> /tmp/include-disk
echo volgroup vg pv.1  >> /tmp/include-disk
echo logvol swap --fstype="swap" --name=swap --vgname=vg --size=512 >> /tmp/include-disk
echo logvol / --fstype="ext4" --size=1024 --name=root --vgname=vg --grow >> /tmp/include-disk

%end

text

# Keyboard layouts
keyboard fr

# Root password
rootpw --iscrypted $y$j9T$fUhioar4.fxiALIegdGuM0$/Jv5ivrvEd/whXgxaEEoQ.4T0mYLG8PJ1BsiETi50/1
sshpw  --iscrypted --username=root $y$j9T$fUhioar4.fxiALIegdGuM0$/Jv5ivrvEd/whXgxaEEoQ.4T0mYLG8PJ1BsiETi50/1
sshkey --username=root "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAgEApP8+6F9A8jKEHG2fPsoatIqIa89K9kUyvf0KCmZQqdPf/WgUWIY3OTJftL8McK8GpErx8u41V/pEtFMXs/cYxkio2hSiwYes4U8uxG3R6VIBjAsC4F2ca58jmQDlXeqaiTGg7Qv5KDthpdCRHjprf0YOnhOafOARflMidsonaJJCP2QJj+Ld796OesUkdTkL0ln3a0iB0B7LOBSeUj0UZQMKrEOnExRasl1hVhuxzImYnyjiDP8+yaG5WhzFrwCNKD7+Ov60IzhiMFFGk44qoLEv71DOpKvCcFVE+39Pd7E9LE8FW6jhgN3gpPDsZncTtICKwQRo0xQwfUXXfP/fWGKyx2AIuod7poesDeaZIcrNFt6QPGnt88jnaDbg/TUaTSGvOatgm5G4uaqFyJQvnaWXJP1XX6J5cWIB8syBUQmwUEqPG37qH0DRMxySMGQOWh2vSQO1uHiDOTQ90j5aCGj1DCdfEpNJVHZO4ub/5HPDVshOamrI2L5F7Wm83LMBCVT31F2tRyohqZ3RmZ/sksLpUDvqXPRukf7AUCzKjMOr7ECY4fehZbMV+JITrtC600gofLrEsPZIb21Q3oaIXLFGbOJkMWWu1YjvftzulVR6hrmfLhoyTmD2DUwmTTKoyZ9JVyS7KoMvk3fHBXThxN+R7A83BTFZEvcmWRd9LWc= DavidOlivier"

# System language
lang fr_FR.UTF-8

# Shutdown after installation
reboot

# Network information
network  --bootproto=dhcp --device=link --activate

# Firewall configuration
#firewall --enabled --service=ssh,cockpit,cockpit-ws

# Use network installation
url --url=http://ftp.lip6.fr/ftp/pub/linux/distributions/fedora/releases/40/Server/x86_64/os/

repo --name=fedora --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-40&arch=x86_64
repo --name=updates --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=updates-released-f40&arch=x86_64
repo --name=adadov --baseurl=http://repo.adadov.loc/adadov/40/x86_64/

# System timezone
timezone Europe/Paris

# SELinux configuration
selinux --disabled

firstboot --disable

# System services
services --enabled="NetworkManager,chronyd"

# System bootloader configuration
bootloader --append="inst.console=ttyS0,115200 inst.console=tty0 inst.selinux=0 inst.audit=0 inst.gpt inst.sshd" --timeout=5

# Clear the Master Boot Record
zerombr

# # Partition clearing information
clearpart --all --disklabel=gpt

%include /tmp/include-disk

%packages 
@core 
@minimal-environment
#@workstation-product-environment
glibc-langpack-en
-NetworkManager-wifi
-ModemManager*
-iw
#-@standard
-generic-release*
-glibc-all-langpacks
-initial-setup-gui
-iproute-tc
-trousers
-puppet
-nano
adadov-repo
cloud-init
bash-completion
qemu-guest-agent
bind-utils
sysstat
htop
vim
vim-default-editor
wget 
tuned
cockpit
cockpit-bridge
cockpit-networkmanager
cockpit-system
cockpit-storaged
cronie-noanacron
rsync
wksconf
#cockpit-pcp


%end

#%post --interpreter=/usr/bin/bash 
#wget -O /etc/pki/ca-trust/source/anchors/dovconnect-pki.pem http://dl.adadov.loc/rootca.pem
#update-ca-trust
#
#echo "kernel.panic = 10"  >> /etc/sysctl.d/kernel.conf
#echo "vm.swappiness = 10" >> /etc/sysctl.d/optimize.conf
#
#
#
#
#%end
